-- 1. Независимые таблицы без внешних ключей
CREATE TABLE IF NOT EXISTS genres (
                                      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      name VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS mpas (
                                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    name VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS directors (
                                         id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         name VARCHAR(30) NOT NULL
);

-- 2. Основные сущности
CREATE TABLE IF NOT EXISTS users (
                                     id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     email VARCHAR(30) NOT NULL,
                                     login VARCHAR(50) NOT NULL,
                                     name VARCHAR(50),
                                     birthday DATE
);

CREATE TABLE IF NOT EXISTS films (
                                     id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(30),
                                     description VARCHAR(200),
                                     release_date DATE,
                                     duration INT,
                                     director_id INT,
                                     mpa_id INT,
                                     CONSTRAINT films_mpa_fk FOREIGN KEY (mpa_id) REFERENCES mpas(id),
                                     CONSTRAINT films_director_fk FOREIGN KEY (director_id) REFERENCES directors(id)
);

-- 3. Связующие таблицы (остаются без изменений)
CREATE TABLE IF NOT EXISTS films_genres (
                                            film_id INT NOT NULL,
                                            genre_id INT NOT NULL,
                                            CONSTRAINT films_genres_film_fk FOREIGN KEY (film_id) REFERENCES films(id),
                                            CONSTRAINT films_genres_genre_fk FOREIGN KEY (genre_id) REFERENCES genres(id),
                                            PRIMARY KEY (film_id, genre_id)
);

-- ... остальные таблицы без изменений